name: load_file

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1.'
        required: true
        default: 'default_value1'
      input2:
        description: 'Input 2'
        required: true
        default: 'default_value2'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Input 1: ${{ inputs.input1 }}"
          echo "Input 2: ${{ inputs.input2 }}"
