name: Load Test

on:
  workflow_dispatch:

jobs:
  run_load_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]

    steps:
      - name: Trigger Workflow
        run: |
          combination="${{ matrix.version }}"
          echo "Combination: $combination"
          octokit="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"
          echo "Octokit: $octokit"
          owner="${{ github.repository_owner }}"
          echo "Owner: $owner"
          repo="${{ github.event.repository.name }}"
          echo "Repository: $repo"
          workflow_content=$(curl -s -H "Authorization: Bearer $octokit" "https://api.github.com/repos/$owner/$repo/actions/workflows/load_file.yml")
          echo $workflow_content
        #   workflow_content=$(curl -s -H "Authorization: token $octokit" "https://raw.githubusercontent.com/ashutoshbajpai007/test1/master/.github/workflows/load_file.yml")
        #   workflow_id=$(echo "$workflow_content" | grep -oP '(?<=id: )\w+')
        #   echo "Workflow ID: $workflow_id"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
