name: Load Test

on:
  workflow_dispatch:
    inputs:
      CHECK:
        description: 'Invoke Job' 
        type: string
        required: true

jobs:
  run_load_test:
    runs-on: self-hosted
    strategy:
      matrix:
        workflow_name: [load_file]  # Specify the names of the workflows to trigger

    steps:
      - name: Trigger ${{ matrix.workflow_name }} workflow
        uses: actions/github-script@v5
        with:
          script: |
            const { data: workflowRuns } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: `.github/workflows/${{ matrix.workflow_name }}.yaml`
            });

            // Trigger workflow
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowRuns.workflow_id,
              ref: 'master'  // Specify the branch or ref to trigger the workflow from
            });
