name: Load Test

on:
  workflow_dispatch:

jobs:
  run_load_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]

    steps:
      - name: Trigger Workflow
        run: |
          combination="${{ matrix.version }}"
          echo $combination
          octokit=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
          echo $octokit
          owner=${{ github.repository_owner }}
          echo $owner
          repo=$(echo -n "${{ github.event.repository.name }}" | jq -r '@uri')
          echo $repo
